
let game = {
    name: "Rock, Paper and Scissors",
    owner: "Me",
    useFor: "Exercise 20",

    choice: ["ROCK", "PAPER", "SCISSORS"],
    winner: `<i class ="text-danger fa fa-beat-fade winner">W i n n e r!</i>`,
    loser: `<i class ="text-dark fa loser">Try Again</i>`,
    // yourScore: `<input id="yScore" type="number" min=0>` ,
    // computerScore: `<input id="cScore" type="number" min=0>` ,
    //Function of the game
    theGame(userChoice) {

        let leftHands = document.querySelectorAll(".hide-lefthands");
        for(let i=0; i<leftHands.length;i++) {
            // leftHands[i].classList.add("hide-lefthands");
            leftHands[i].classList.remove("show-lefthands");
        }

        let rightHands = document.querySelectorAll(".hide-righthands");
        for(let i=0; i<rightHands.length;i++) {
            // rightHands[i].classList.add("hide-righthands");
            rightHands[i].classList.remove("show-righthands");
           
        }

       
        //insert button behavior
        // function selectBtn() {
            let buttons = document.querySelectorAll(".allButtons"); //check all the buttons and clear the background
            for (let index = 0; index < buttons.length; index++) {
                    buttons[index].classList.remove("button-active");
            }
            event.target.classList.add("button-active"); //where the event happens, that would be the target of the attribute.add 
       

    //Generate Random Number
    let uChoice = Number(userChoice);
    let rNumber = Math.random();
   
    // let mCeil = Math.ceil(rNumber) * 3;
    // let mFloor = Math.floor(rNumber* 3);
    let mRound = Math.round(rNumber * 2);
    // alert(mRound);
    // alert("Your choice is: " + uChoice);
    // Evaluates user choice from index file and compare with rounded randome number generated by random() method
    switch (uChoice) {
        case 0: 

            let leftRock = document.getElementById("leftRock");
            leftRock.classList.remove("show-lefthands");
            leftRock.classList.add("show-lefthands");
         
            if (mRound == 0) {
                
                let Result = "Rock DOESN'T beat Rock";
                let Status = "It's a DRAW, Try again!";
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 0;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 0;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 1;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Rock) VS Rock, it's a draw.</li>");

                
                let rightRock = document.getElementById("rightRock");
                rightRock.classList.remove("show-righthands");
                rightRock.classList.add("show-righthands");

                
            }else if(mRound == 1) { //Computer random choice is 1 = paper
                let Result = "Rock DOESN'T beat Paper";
                let Status = "You LOSE!";
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 0;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 1;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 0;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Rock) VS Paper, you lost.</li>");

           
                let rightPaper = document.getElementById("rightPaper");
                rightPaper.classList.remove("show-righthands");
                rightPaper.classList.add("show-righthands");


            } else if (mRound == 2) {
                let Result = "Rock BEATS Scissors";
                let Status =`<i class ="text-danger fa fa-beat-fade winner">YOU WIN!</i>`;
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 1;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 0;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 0;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Rock) VS Scissors, you win.</li>");

                let rightScissors = document.getElementById("rightScissors");
                rightScissors.classList.remove("show-righthands");
                rightScissors.classList.add("show-righthands");

            }else {
                alert("Something went wrong, case 0");
            }
            break;
         case 1: 
            let leftPaper = document.getElementById("leftPaper");
            leftPaper.classList.remove("show-lefthands");
            leftPaper.classList.add("show-lefthands");
        
            if (mRound == 0) {
                let Result = "Paper BEATS Rock";
                let Status = `<i class ="text-danger fa fa-beat-fade winner">YOU WIN!</i>`;
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 1;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 0;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 0;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Paper) VS Rock, you won.</li>");

                let rightRock = document.getElementById("rightRock");
                rightRock.classList.remove("show-righthands");
                rightRock.classList.add("show-righthands");

                
            }else if(mRound == 1) { //Computer random choice is 1 = paper
                let Result = "Paper DOESN'T beat Paper";
                let Status = "It's a DRAW, Try again!";
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 0;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 0;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 1;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Paper) VS Paper, it's a draw.</li>");
   
                let rightPaper = document.getElementById("rightPaper");
                rightPaper.classList.remove("show-righthands");
                rightPaper.classList.add("show-righthands");


            } else if (mRound == 2) {
                let Result = "Paper DOESN'T beat Scissors";
                let Status = "You LOSE!";
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                // let winScore = Number(document.getElementById("score").value);
                // document.getElementById("score").value = winScore + 0;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 0;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 1;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 0;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Paper) VS Scissors, you lose.</li>");
 
                let rightRock = document.getElementById("rightRock");
                rightRock.classList.remove("show-righthands");
                rightRock.classList.add("show-righthands");

            }else {
                alert("Something went wrong, case 1");
            }
            break;
        case 2: 
         let leftScissors = document.getElementById("leftScissors");
            leftScissors.classList.remove("show-lefthands");
            leftScissors.classList.add("show-lefthands");
        
            if (mRound == 0) {
                let Result = "Scissors DOESN'T beat Rock";
                let Status = "You LOSE";
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 0;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 1;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 0;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Scissors) VS Rock, you lost.</li>");

                let rightRock = document.getElementById("rightRock");
                rightRock.classList.remove("show-righthands");
                rightRock.classList.add("show-righthands");

                
            }else if(mRound == 1) { //Computer random choice is 1 = paper
                let Result = "Scissors BEAT Paper";
                let Status = `<i class ="text-danger fa fa-beat-fade winner">YOU WIN!</i>`;
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                  let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 1;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 0;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 0;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Scissors) VS Paper, you win.</li>");
    
                let rightPaper = document.getElementById("rightPaper");
                rightPaper.classList.remove("show-righthands");
                rightPaper.classList.add("show-righthands");



            } else if (mRound == 2) {
                let Result = "Scissors DOESN'T Scissors";
                let Status = "It's a DRAW, Try again!";
                let gameHistory = document.getElementById("gameHistory");

                document.getElementById("outputHeading").innerHTML = Result;
                document.getElementById("outputSubHeading").innerHTML = Status;

                let winScore = Number(document.getElementById("wscore").value);
                document.getElementById("wscore").value = winScore + 0;
                let loseScore = Number(document.getElementById("lscore").value);
                document.getElementById("lscore").value = loseScore + 0;
                let drawScore = Number(document.getElementById("dscore").value);
                document.getElementById("dscore").value = drawScore + 1;

                gameHistory.insertAdjacentHTML("afterbegin", "<li>Your choice (Scissors) VS Scissors, it's a draw.</li>");


                let rightRock = document.getElementById("rightRock");
                rightRock.classList.remove("show-righthands");
                rightRock.classList.add("show-righthands");

            }else {
                alert("Something went wrong, case 2")
           }
        break;
        default: alert("Something went wrong, case end")
    }


    
    },

};
//game.theGame();